### ISSUE TITLE
Function to search across _all_ styles

### ISSUE THREAD

**Issue by benui-dev** [sirjofri/SlateIconBrowser#2]
I would love to be able to search for a string across all styles, and the results listed with the associated style

**Comment by sirjofri** [comment]
This (and the others) are good suggestions and I'd like to add them. I'm just busy with another (smaller) Unreal tool I want to publish soon, which is almost finished, then I'll improve SlateIconBrowser. 🙂

**Comment by sirjofri** [comment]
done :)
